version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: metrix_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Subhash@8729
      MYSQL_DATABASE: metrix_r76
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/schema/full.sql:/docker-entrypoint-initdb.d/01-full.sql
      - ../database/seeds/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    container_name: metrix_backend
    restart: always
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: Subhash@8729
      DB_NAME: metrix_r76
      JWT_SECRET: METRIX_R76_DOCA_SECRET_KEY_2026_LEGAL_METROLOGY_COMPLIANCE
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: metrix_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  uploads_data:
